const session = {
  id: "cs_test_a14k4s8VbIcoBUezde3Uu4JMoC1Y9AqxM9URJreIkH9qA9Mt8rMV03rPLM",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 9900,
  amount_total: 9900,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url: "http://localhost:3000/cancel",
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1717131208,
  currency: "gbp",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "always",
  customer_details: {
    address: null,
    email: "customer@gmail.com",
    name: null,
    phone: null,
    tax_exempt: "none",
    tax_ids: null,
  },
  customer_email: "customer@gmail.com",
  expires_at: 1717217608,
  invoice: null,
  invoice_creation: null,
  livemode: false,
  locale: null,
  metadata: {},
  mode: "subscription",
  payment_intent: null,
  payment_link: null,
  payment_method_collection: "always",
  payment_method_configuration_details: null,
  payment_method_options: { card: { request_three_d_secure: "automatic" } },
  payment_method_types: ["card"],
  payment_status: "unpaid",
  phone_number_collection: { enabled: false },
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: ["always"],
    payment_method_remove: null,
    payment_method_save: null,
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_details: null,
  shipping_options: [],
  status: "open",
  submit_type: null,
  subscription: null,
  success_url: "http://localhost:3000/success",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: "https://checkout.stripe.com/c/pay/cs_test_a14k4s8VbIcoBUezde3Uu4JMoC1Y9AqxM9URJreIkH9qA9Mt8rMV03rPLM#fidkdWxOYHwnPyd1blpxYHZxWjA0VU9kMXdWQlNDVzx%2FYUdJc2Zva3Vcc0NiS1BAUUcwN39BNjF%2FPEZtSUByYXRVYjFzUEh8XUtvUEN%2FaGlgPUFPdH1dMVV3SUJMbTNRa0lSQEB0VGtqYWtsNTVGfTRKVH9KVicpJ2N3amhWYHdzYHcnP3F3cGApJ2lkfGpwcVF8dWAnPyd2bGtiaWBabHFgaCcpJ2BrZGdpYFVpZGZgbWppYWB3dic%2FcXdwYHgl",
};

const subscription = {
  id: "sub_1PMNTjSGVFR9zdBLIBRvDBVc",
  object: "subscription",
  application: null,
  application_fee_percent: null,
  automatic_tax: { enabled: false, liability: null },
  billing_cycle_anchor: 1717131251,
  billing_cycle_anchor_config: null,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  cancellation_details: { comment: null, feedback: null, reason: null },
  collection_method: "charge_automatically",
  created: 1717131251,
  currency: "gbp",
  current_period_end: 1719723251,
  current_period_start: 1717131251,
  customer: "cus_QCn3aCOd2KKDZe",
  days_until_due: null,
  default_payment_method: "pm_1PMNTiSGVFR9zdBLJRY09vdU",
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  ended_at: null,
  invoice_settings: { account_tax_ids: null, issuer: { type: "self" } },
  items: {
    object: "list",
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: "/v1/subscription_items?subscription=sub_1PMNTjSGVFR9zdBLIBRvDBVc",
  },
  latest_invoice: "in_1PMNTjSGVFR9zdBLk0bEIxxo",
  livemode: false,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
    save_default_payment_method: "off",
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: "price_1PLkRPSGVFR9zdBLL1rqX7xv",
    object: "plan",
    active: true,
    aggregate_usage: null,
    amount: 9900,
    amount_decimal: "9900",
    billing_scheme: "per_unit",
    created: 1716981191,
    currency: "gbp",
    interval: "month",
    interval_count: 1,
    livemode: false,
    metadata: {},
    meter: null,
    nickname: null,
    product: "prod_QC8irL0zmoaRJD",
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: "licensed",
  },
  quantity: 1,
  schedule: null,
  start_date: 1717131251, 
  status: "active",
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: {
    end_behavior: { missing_payment_method: "create_invoice" },
  },
  trial_start: null,
};

const invoice = {
  id: "in_1PMNTjSGVFR9zdBLk0bEIxxo",
  object: "invoice",
  account_country: "IN",
  account_name: null,
  account_tax_ids: null,
  amount_due: 9900,
  amount_paid: 9900,
  amount_remaining: 0,
  amount_shipping: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 1,
  attempted: true,
  auto_advance: false,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_reason: "subscription_create",
  charge: "ch_3PMNTjSGVFR9zdBL1yWFjvDl",
  collection_method: "charge_automatically",
  created: 1717131251,
  currency: "gbp",
  custom_fields: null,
  customer: "cus_QCn3aCOd2KKDZe",
  customer_address: {
    city: "Rajkot",
    country: "IN",
    line1: "address1",
    line2: "address2",
    postal_code: "360003",
    state: "GJ",
  },
  customer_email: "customer@gmail.com",
  customer_name: "Customer 1",
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: null,
  effective_at: 1717131251,
  ending_balance: 0,
  footer: null,
  from_invoice: null,
  hosted_invoice_url:
    "https://invoice.stripe.com/i/acct_1PJa4rSGVFR9zdBL/test_YWNjdF8xUEphNHJTR1ZGUjl6ZEJMLF9RQ24zUk9Temo3dnNlQjliRUNLT0dUSnd4NzhScEdPLDEwNzY3MjA1OQ0200rbF6DFWu?s=ap",
  invoice_pdf:
    "https://pay.stripe.com/invoice/acct_1PJa4rSGVFR9zdBL/test_YWNjdF8xUEphNHJTR1ZGUjl6ZEJMLF9RQ24zUk9Temo3dnNlQjliRUNLT0dUSnd4NzhScEdPLDEwNzY3MjA1OQ0200rbF6DFWu/pdf?s=ap",
  issuer: { type: "self" },
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: "list",
    data: [[Object]],
    has_more: false,
    total_count: 1,
    url: "/v1/invoices/in_1PMNTjSGVFR9zdBLk0bEIxxo/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: "61D582CC-0001",
  on_behalf_of: null,
  paid: true,
  paid_out_of_band: false,
  payment_intent: "pi_3PMNTjSGVFR9zdBL1VRIOLVb",
  payment_settings: {
    default_mandate: null,
    payment_method_options: {
      acss_debit: null,
      bancontact: null,
      card: [Object],
      customer_balance: null,
      konbini: null,
      sepa_debit: null,
      us_bank_account: null,
    },
    payment_method_types: null,
  },
  period_end: 1717131251,
  period_start: 1717131251,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  quote: null,
  receipt_number: null,
  rendering: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "paid",
  status_transitions: {
    finalized_at: 1717131251,
    marked_uncollectible_at: null,
    paid_at: 1717131256,
    voided_at: null,
  },
  subscription: "sub_1PMNTjSGVFR9zdBLIBRvDBVc",
  subscription_details: { metadata: {} },
  subtotal: 9900,
  subtotal_excluding_tax: 9900,
  tax: null,
  test_clock: null,
  total: 9900,
  total_discount_amounts: [],
  total_excluding_tax: 9900,
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: 1717131257,
};
console.log("Subscription ID: sub_1PMNTjSGVFR9zdBLIBRvDBVc");
console.log("Invoice ID: in_1PMNTjSGVFR9zdBLk0bEIxxo");

console.log(
  "Subscription Start Date: Fri May 31 2024 10:24:11 GMT+0530 (India Standard Time)"
);
console.log(
  "Subscription End Date: Sun Jun 30 2024 10:24:11 GMT+0530 (India Standard Time)"
);
console.log("Invoice Total: 9900");

const temp = {
  object: {
    id: "in_1PMT7OSGVFR9zdBLMJCfZ9oW",
    object: "invoice",
    account_country: "IN",
    account_name: null,
    account_tax_ids: null,
    amount_due: 19900,
    amount_paid: 0,
    amount_remaining: 19900,
    amount_shipping: 0,
    application: null,
    application_fee_amount: null,
    attempt_count: 0,
    attempted: false,
    auto_advance: false,
    automatic_tax: {
      enabled: false,
      liability: null,
      status: null,
    },
    billing_reason: "subscription_create",
    charge: null,
    collection_method: "charge_automatically",
    created: 1717152930,
    currency: "gbp",
    custom_fields: null,
    customer: "cus_QCsrxGJfB0h13r",
    customer_address: null,
    customer_email: "roman@gmail.com",
    customer_name: "Roman",
    customer_phone: null,
    customer_shipping: null,
    customer_tax_exempt: "none",
    customer_tax_ids: [],
    default_payment_method: null,
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    discounts: [],
    due_date: null,
    effective_at: 1717152930,
    ending_balance: 0,
    footer: null,
    from_invoice: null,
    hosted_invoice_url:
      "https://invoice.stripe.com/i/acct_1PJa4rSGVFR9zdBL/test_YWNjdF8xUEphNHJTR1ZGUjl6ZEJMLF9RQ3N0UmlUYmp3aGRJT3FuRGZBMEcwN0Z4VDFLM1pPLDEwNzY5MzczMQ0200X7Q3ooIt?s=ap",
    invoice_pdf:
      "https://pay.stripe.com/invoice/acct_1PJa4rSGVFR9zdBL/test_YWNjdF8xUEphNHJTR1ZGUjl6ZEJMLF9RQ3N0UmlUYmp3aGRJT3FuRGZBMEcwN0Z4VDFLM1pPLDEwNzY5MzczMQ0200X7Q3ooIt/pdf?s=ap",
    issuer: {
      type: "self",
    },
    last_finalization_error: null,
    latest_revision: null,
    lines: {
      object: "list",
      data: [
        {
          id: "il_1PMT7OSGVFR9zdBLAj1S16mj",
          object: "line_item",
          amount: 19900,
          amount_excluding_tax: 19900,
          currency: "gbp",
          description: "1 × Standard (at £199.00 / month)",
          discount_amounts: [],
          discountable: true,
          discounts: [],
          invoice: "in_1PMT7OSGVFR9zdBLMJCfZ9oW",
          livemode: false,
          metadata: {},
          period: {
            end: 1719744930,
            start: 1717152930,
          },
          plan: {
            id: "price_1PMT3KSGVFR9zdBLsJlaauUG",
            object: "plan",
            active: true,
            aggregate_usage: null,
            amount: 19900,
            amount_decimal: "19900",
            billing_scheme: "per_unit",
            created: 1717152678,
            currency: "gbp",
            interval: "month",
            interval_count: 1,
            livemode: false,
            metadata: {},
            meter: null,
            nickname: null,
            product: "prod_QCsoYQQQst7WD5",
            tiers_mode: null,
            transform_usage: null,
            trial_period_days: null,
            usage_type: "licensed",
          },
          price: {
            id: "price_1PMT3KSGVFR9zdBLsJlaauUG",
            object: "price",
            active: true,
            billing_scheme: "per_unit",
            created: 1717152678,
            currency: "gbp",
            custom_unit_amount: null,
            livemode: false,
            lookup_key: null,
            metadata: {},
            nickname: null,
            product: "prod_QCsoYQQQst7WD5",
            recurring: {
              aggregate_usage: null,
              interval: "month",
              interval_count: 1,
              meter: null,
              trial_period_days: null,
              usage_type: "licensed",
            },
            tax_behavior: "unspecified",
            tiers_mode: null,
            transform_quantity: null,
            type: "recurring",
            unit_amount: 19900,
            unit_amount_decimal: "19900",
          },
          proration: false,
          proration_details: {
            credited_items: null,
          },
          quantity: 1,
          subscription: "sub_1PMT7OSGVFR9zdBLFzdMHQjE",
          subscription_item: "si_QCstAU1Z3g7xYL",
          tax_amounts: [],
          tax_rates: [],
          type: "subscription",
          unit_amount_excluding_tax: "19900",
        },
      ],
      has_more: false,
      total_count: 1,
      url: "/v1/invoices/in_1PMT7OSGVFR9zdBLMJCfZ9oW/lines",
    },
    livemode: false,
    metadata: {},
    next_payment_attempt: null,
    number: "AA71C90B-0001",
    on_behalf_of: null,
    paid: false,
    paid_out_of_band: false,
    payment_intent: "pi_3PMT7OSGVFR9zdBL1DeCQyxH",
    payment_settings: {
      default_mandate: null,
      payment_method_options: {
        acss_debit: null,
        bancontact: null,
        card: {
          request_three_d_secure: "automatic",
        },
        customer_balance: null,
        konbini: null,
        sepa_debit: null,
        us_bank_account: null,
      },
      payment_method_types: null,
    },
    period_end: 1717152930,
    period_start: 1717152930,
    post_payment_credit_notes_amount: 0,
    pre_payment_credit_notes_amount: 0,
    quote: null,
    receipt_number: null,
    rendering: null,
    shipping_cost: null,
    shipping_details: null,
    starting_balance: 0,
    statement_descriptor: null,
    status: "open",
    status_transitions: {
      finalized_at: 1717152930,
      marked_uncollectible_at: null,
      paid_at: null,
      voided_at: null,
    },
    subscription: "sub_1PMT7OSGVFR9zdBLFzdMHQjE",
    subscription_details: {
      metadata: {},
    },
    subtotal: 19900,
    subtotal_excluding_tax: 19900,
    tax: null,
    test_clock: null,
    total: 19900,
    total_discount_amounts: [],
    total_excluding_tax: 19900,
    total_tax_amounts: [],
    transfer_data: null,
    webhooks_delivered_at: null,
  },
};

